default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  password: password

development:
  <<: *default
  database: rails_and_react_development

test:
  <<: *default
  database: rails_and_react_test

production:
  <<: *default
  database: rails_and_react_production
